name: Deploy to GKE
on:
  push:
    branches:
      - develop
permissions: 
  contents: read
  id-token: write
jobs:
  set_env:
    outputs:
      current_env: ${{ steps.setenv.outputs.current_env }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: |
          if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "current_env=production" >> $GITHUB_OUTPUT
          else
            echo "current_env=develop" >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: set_env
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      ZONE: us-east4
    environment: 
      name: ${{ needs.set_env.outputs.current_env }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ vars.IDENTITY_PROVIDER }} 
        service_account: ${{ vars.SERVICE_ACCOUNT }} 
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
        project_id: ${{ vars.PROJECT_ID }}
    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ vars.CLUSTER_NAME }}
        location: us-east4
        project_id: ${{ vars.PROJECT_ID }}


    # - name: Apply deployment
    #   run: |
    #     kubectl apply -k envs/gke
