name: Deploy to GKE
on:
  push:
    branches:
      - develop
      - main
permissions: 
  contents: read
  id-token: write
jobs:
  set_env:
    outputs:
      current_env: ${{ steps.setenv.outputs.current_env }}
    runs-on: ubuntu-latest
    steps:
      - id: setenv
        run: |
          if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "current_env=production" >> $GITHUB_OUTPUT
          else
            echo "current_env=develop" >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: set_env
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      ZONE: us-east4
    environment: 
      name: ${{ needs.set_env.outputs.current_env }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ vars.IDENTITY_PROVIDER }} 
        service_account: ${{ vars.SERVICE_ACCOUNT }} 
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
        project_id: ${{ vars.PROJECT_ID }}
    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ vars.CLUSTER_NAME }}
        location: us-east4
        project_id: ${{ vars.PROJECT_ID }}
    - name: Apply K8s Manifests
      run: |
        kubectl delete namespace wazuh --ignore-not-found
        kubectl create namespace wazuh

        kubectl delete secret dashboard-cred --ignore-not-found -n wazuh
        kubectl create secret generic dashboard-cred --from-literal=username=${{ secrets.DASHBOARD_USERNAME }} --from-literal=password=${{ secrets.DASHBOARD_PASSWORD }} -n wazuh

        kubectl delete secret indexer-cred --ignore-not-found -n wazuh
        kubectl create secret generic indexer-cred --from-literal=username=${{ secrets.INDEXER_USERNAME }} --from-literal=password=${{ secrets.INDEXER_PASSWORD }} -n wazuh
        
        kubectl delete secret wazuh-api-cred --ignore-not-found -n wazuh
        kubectl create secret generic wazuh-api-cred --from-literal=username=${{ secrets.API_USERNAME }} --from-literal=password=${{ secrets.API_PASSWORD }} -n wazuh
        
        kubectl delete secret generic wazuh-authd-pass --ignore-not-found -n wazuh
        kubectl create secret generic wazuh-authd-pass --from-literal=authd.pass=${{ secrets.AUTH_D_PASSWORD }} -n wazuh
        
        kubectl delete secret wazuh-cluster-key --ignore-not-found -n wazuh
        kubectl create secret generic wazuh-cluster-key --from-literal=key=${{ secrets.CLUSTER_KEY }} -n wazuh

        cd wazuh/certs/dashboard_http

        echo 'Generating dashboard certs...'

        sh generate_certs.sh

        cd ..

        cd indexer_cluster

        echo 'Generating index cluster certs...'

        sh generate_certs.sh

        echo 'Applying k8s manifests...'

        cd ../../..

        kubectl apply -k envs/gke

        
